name: ml-proj-dsti
dependencies:
  - python==3.10.4
  - dill==0.3.8
  - notebook==7.3.2
  - pandas==2.1.4
  - scipy==1.15.1
  - scikit-learn==1.6.1
  - seaborn==0.13.2
  - pip==25.0
  - pip:
      - ipaddress==1.0.23
      - python-dotenv==1.0.1
      - user-agents==2.2.0
